# Generated by Django 5.0.3 on 2024-03-12 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='Employee', max_length=50, null=True, verbose_name='Position:')),
                ('address', models.CharField(default='Köllner St', max_length=50, null=True, verbose_name='Address:')),
                ('city', models.CharField(default='Düsseldorf', max_length=50, null=True, verbose_name='City:')),
                ('state', models.CharField(default='NRW', max_length=50, null=True, verbose_name='State:')),
                ('zip_nummber', models.CharField(default='111', max_length=50, null=True, verbose_name='Zip Number:')),
                ('description', models.TextField(blank=True, default='Hi, I’m user, Decisions: this is a place to add desc about you', null=True)),
                ('mobile', models.CharField(blank=True, default='+49 1231234123', max_length=15, null=True)),
                ('twitter_profile', models.URLField(blank=True, default='', null=True)),
                ('facebook_profile', models.URLField(blank=True, default='', null=True)),
                ('instagram_profile', models.URLField(blank=True, default='', null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics/%Y%m/%d')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='products.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
