# Generated by Django 5.0.3 on 2024-03-12 23:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='21', max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price $')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('Conversion_ratio', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('desc', models.CharField(default='', max_length=100, null=True, verbose_name='Desc: ')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('startWork', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.CharField(default='kette', max_length=50, null=True, verbose_name='Name: ')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='available', max_length=50, unique=True)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.CharField(default='', max_length=100, null=True, verbose_name='Desc: ')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ring', max_length=50, unique=True)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.CharField(default='', max_length=100, null=True, verbose_name='Desc: ')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default='123123123', max_length=50, unique=True, verbose_name='BarCode:')),
                ('pin', models.CharField(default='123456', max_length=10, unique=True, verbose_name='PinCode:')),
                ('name', models.CharField(default='kette', max_length=50, null=True, verbose_name='Name: ')),
                ('size', models.IntegerField(default=10, null=True)),
                ('price_sold', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Sold Price $:')),
                ('weight', models.DecimalField(decimal_places=3, default=10, max_digits=7, verbose_name='Weight G:')),
                ('is_quantity', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('desc', models.CharField(default='', max_length=100, null=True, verbose_name='Desc: ')),
                ('description', models.TextField(blank=True, default='this is place for description', null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('sell_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(default='default_pro.jpg', upload_to='products/%Y/%m/%d')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_pro', to='products.classes')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_pro', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_pro', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_pro', to='products.shop')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_pro', to='products.status')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_pro', to='products.types')),
            ],
            options={
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='UpdateProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.CharField(default='', max_length=100, null=True, verbose_name='Desc: ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_update', to='products.products')),
            ],
            options={
                'ordering': ['update_time'],
            },
        ),
    ]
